name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Dist Folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Ensure this generates a 'dist' folder

      - name: Push `dist` Folder to `build` Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build  # The branch where only 'dist' will be pushed
          FOLDER: dist  # Change this if your build output is different
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"
