name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main  # Trigger on main branch push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Dist Folder
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install  # Install dependencies for both TypeScript and Vite
          echo "Dependencies installed."

      - name: Check Node Version (Optional)
        run: |
          echo "Node version:"
          node --version  # Check if node is available for troubleshooting

      - name: Check npm Version (Optional)
        run: |
          echo "NPM version:"
          npm --version  # Ensure npm is available

      - name: Compile TypeScript and Build with Vite
        run: |
          echo "Running TypeScript compilation..."
          tsc -b  # Compile TypeScript (if using project references)
          echo "Running Vite build..."
          npm run build  # Build with Vite

      - name: Check for dist folder
        run: |
          echo "Listing contents of dist folder:"
          ls -l dist  # List contents of dist to verify if it's generated

      - name: Deploy Only `dist` to `build` Branch
        run: |
          echo "Setting up Git for deployment..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          echo "Checking out the build branch..."
          git checkout build || git checkout --orphan build
          
          echo "Removing unnecessary files..."
          rm -rf .github node_modules src public
          
          echo "Moving dist contents to root..."
          mv dist/* . && rm -rf dist  # Move contents of dist to root and remove dist folder
          
          echo "Adding changes to Git..."
          git add .
          git commit -m "Deploy dist folder"
          
          echo "Pushing changes to build branch..."
          git push --force origin build
