name: Build and Deploy Dist to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Dist Folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  # Install dependencies for TypeScript and Vite

      - name: Build Project
        run: |
          tsc -b  # Compile TypeScript if you have project references
          npm run build  # Build with Vite

      - name: Check dist folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "dist folder not found, exiting!";
            exit 1;
          fi

      - name: Checkout or create build branch
        run: |
          git fetch origin build || true  # Ignore errors if branch doesn't exist
          git checkout build || git checkout --orphan build
          
          git reset --hard origin/build || true
          git clean -fd

      - name: Deploy Only dist to build Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          rm -rf .github node_modules src public
          
          mv dist/* . && rm -rf dist
          
          git add .
          git commit -m "Deploy dist folder"
          
          git push --force origin build  # Force push to overwrite without conflicts

      - name: Trigger Webhook
        run: |
          echo "Triggering webhook..."
          curl -X POST \
               -H "Content-Type: application/x-www-form-urlencoded" \
               --data "status=success" \
               https://webhooks.hostinger.com/deploy/58d0f711aa61264ec48c1ab4fd2be002
