name: Build and Deploy Dist to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Dist Folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  # Install dependencies for TypeScript and Vite

      - name: Build Project
        run: |
          tsc -b  # Compile TypeScript if you have project references
          npm run build  # Build with Vite

      - name: Check dist folder
        run: |
          ls -l dist  # List contents of dist folder to ensure it's created

      - name: Deploy Only dist to build Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git checkout build || git checkout --orphan build
          
          rm -rf .github node_modules src public
          
          mv dist/* . && rm -rf dist
          
          git add .
          git commit -m "Deploy dist folder"
          
          git push --force origin build  # Force push to overwrite without conflicts

      # ✅ Webhook trigger after successful deployment
      - name: Trigger Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{"status":"success"}' https://webhooks.hostinger.com/deploy/58d0f711aa61264ec48c1ab4fd2be002 
