name: Build and Deploy Dist to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Dist Folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  # Install dependencies for TypeScript and Vite

      - name: Build Project
        run: |
          tsc -b  # Compile TypeScript if you have project references
          npm run build  # Build with Vite

      - name: Check dist folder
        run: |
          ls -l dist  # List contents of dist folder to ensure it's created

      - name: Deploy Only dist to build Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Fetch latest build branch
          git fetch origin build || true  # Ignore errors if branch doesn't exist

          # Checkout build branch or create it if it doesn't exist
          git checkout build || git checkout --orphan build
          
          # Ensure no old files remain
          git reset --hard origin/build || true
          git clean -fd

          # Remove everything except the dist folder
          rm -rf .github node_modules src public
          
          mv dist/* . && rm -rf dist
          
          git add .
          git commit -m "Deploy dist folder"
          
          # Force push to ensure clean deployment
          git push --force origin build

      - name: Trigger Webhook
        run: |
          curl -X POST \
               -H "Content-Type: application/x-www-form-urlencoded" \
               --data "status=success" \
               https://webhooks.hostinger.com/deploy/58d0f711aa61264ec48c1ab4fd2be002
